title: Chandula Online Resume
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Chandula Karunathilake"
job: "Embedded Systems Engineer"

phone_number: 012-345-6789
address: Gampaha, Sri Lanka
email: chandulanethmal@gmail.com@example.com
linkedin_username: chandula karunathilake
github_username: chandulanethmal
instagram_username: instagram
twitter_username: twitter
facebook_username: thinkerscloud
youtube_username: chandulanethmal
blog_url: chandulanethmal.github.io

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag